### ISSUE TITLE
Specifying multiple calendar_ids doesn't seem to work.

### ISSUE THREAD

**Issue by jaredwindover** [cronofy/cronofy-node#26]
If I specify an array of calendar_ids[] for the free-busy function, it produces a request with a parameter like: calendar_ids[]=cal_calendar_a_id%2Ccal_calendar_b_id
which doesn't work. It gets interpreted as one calendar_id with a comma in the middle, which doesn't exist. I think the calendar_ids[] parameter should be specified once for each element.

**Comment by jaredwindover** [comment]
Seems to be this issue in rest-client: https://github.com/cujojs/rest/issues/124 which was fixed in version 2.0.0 in early 2016. Any chance of that upgrade happening (currently pegged at major version 1)?

**Comment by gshutler** [comment]
A recent release allowed 2.0.0 and up so this should now be resolved.
