### ISSUE TITLE
Consider bulk event delete/insert

### ISSUE THREAD

**Issue by hipitihop** [cronofy/cronofy-node#27]
**My use case:** 
A user can import a CSV file which represents all events for a given week (or a day). My app creates managed events via the `createEvent` API. Also so the user can reload the events (user can modify events outside the calendar and then produce an updated CSV) I use the `deleteEvent` API to clear existing events in the target date range.

**For a full cycle I currently need to:**
- `listEvents` to get all event_id for each existing managed event.
- For each event listed issue `deleteEvent` (about 1 sec per round trip)
- For each new event from CSV use `createEvent` (about 1 sec per round trip)
- For an average of 30 events in a CSV this represents an operation that takes a minute.

**Please consider better support for bulk events in the API:**
- augment the bulk event delete to also allow optional date range, same as list events
- alternately consider augmenting deleteEvent to support optional list of event ids
- augment createEvent to take list of events or create a bulk create event API

I realise this is not a cronofy-node specific issue and would require support in the underlying cronofy API but that's not OSS as afaict.

**Comment by gshutler** [comment]
@hipitihop you're right in thinking we'd need to first deal with this in the Cronofy API before it could be exposed here.

This is something on our roadmap but I'm afraid I can't give any firm commitment on when it will be available as priorities often shift. If you have a developer account then you'll receive a notification once it is available.
