### ISSUE TITLE
Published build folder not correct

### ISSUE THREAD

**Issue by AdriVanHoudt** [cronofy/cronofy-node#31]
Not sure what happened but the published build folder does not contain the latest changes. 
Could you publish a patch version with the correct build asap?

**Comment by gshutler** [comment]
I noticed this about the same time. I think I'd not got latest correctly or something when publishing. v2.3.0 has them in. Sorry about that!

**Comment by AdriVanHoudt** [comment]
No problem! Thanks for the quick response!
