### ISSUE TITLE
entity body sent sent with GET resources

### ISSUE THREAD

**Issue by JulienYo** [cronofy/cronofy-node#35]
_rest_ lib is always called giving an `entity`, even for GET resources.
E.g. for `GET /v1/events` the `from` and `tzid` (and all other optional parameters) are given in the body of the GET (weird, but seems to work), and fails to parse for example the `include_managed` param.

I open a PR for the fix to use `params` when `GET` method [rest doc](https://github.com/cujojs/rest/blob/master/docs/interfaces.md#user-content-common-request-properties)

**Comment by stephenbinns** [comment]
Fixed in #42
