### ISSUE TITLE
Note able to run cronofy-node

### ISSUE THREAD

**Issue by VivekIshir** [cronofy/cronofy-node#51]
@warbrett  HI ,
I am not able to run the Code https://github.com/cronofy/cronofy-node 

Steps Fallowed:
> Clone the Code 
> install npm 
> npm test 
getting error 

![image](https://user-images.githubusercontent.com/34680272/36411671-acff32bc-163c-11e8-9f73-a1a380bcce4e.png)

**Comment by stephenbinns** [comment]
What is the output of `npm test` it looks like you've closed it before it has executed.

**Comment by VivekIshir** [comment]
https://github.com/cronofy/cronofy-node/issues/51#issuecomment-366901709

**Comment by stephenbinns** [comment]
Fixed in master now
