### ISSUE TITLE
There is no update/patch for events? 

### ISSUE THREAD

**Issue by Flos** [cronofy/cronofy-node#52]
I would like to be able to change details of an event, but I can only delete and create events. 
So when I update for example the time, do I have to delete the event and create a new event with the same id? 

What about the metadata which is maybe only in the original agenda provider?

**Comment by gshutler** [comment]
A create is actually an upsert so to update an event you make a "create" request with the new details.

The update should preserve any other metadata for the event if that is what you are concerned about.
