### ISSUE TITLE
`availability_rules` request should be a GET, not POST

### ISSUE THREAD

**Issue by nosajio** [cronofy/cronofy-node#78]
https://github.com/cronofy/cronofy-node/blob/cbb407a6c090e9dae2eb4fd0a58217ea82516109/src/index.js#L205

This is according to the documentation, and confirmed with testing.

**Comment by AdamWhittingham** [comment]
Hi @nosajio 
This has been fixed and released in [v3.5.0](https://www.npmjs.com/package/cronofy/v/3.5.0); thank you for raising it!

**Comment by nosajio** [comment]
My pleasure! Really appreciate the efficient turnaround @AdamWhittingham
